name: Deploy prod
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_supabase_url: ${{ secrets.SUPABASE_URL}}
          CYPRESS_supabase_anon_key: ${{ secrets.SUPABASE_ANON_KEY}}
          CYPRESS_test_account_password: ${{ secrets.TEST_ACCOUNT_PASSWORD}}
          CYPRESS_test_account_email: ${{ secrets.TEST_ACCOUNT_EMAIL}}
          CYPRESS_movie_api_url: ${{ secrets.MOVIE_API_URL }}
        with:
          install-command: npm install --legacy-peer-deps
          build: npm run build
          start: npm start